Repository sherigar/HacktoberFest-2023, pull requests merged in 2023-10, with the labels that each got.

#27 Javascript questions added
  javascript/Factorial.js
  javascript/MaxNumberInArray.js
  javascript/ReverseString.js
  javascript/StringPalindrome.js
  javascript/SumOfTwoNumbers.js
Labels: hacktoberfest, hacktoberfest-accepted

#26 x^n
  java/XpowerN.java
Labels: hacktoberfest, hacktoberfest-accepted

#18 Operations on Matrix in java
  java/MatrixOperation.java
Labels: hacktoberfest, hacktoberfest-accepted

#19 Create Hollow_diamond.cpp
  c++/Hollow_diamond.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#20 valid_anagram is added to python
  python/valid_anagram.py
Labels: hacktoberfest, hacktoberfest-accepted

#21 Create Greatest number among five
  c/Greatest number among five
Labels: hacktoberfest, hacktoberfest-accepted

#22 Create Rotating A Linked List.java
  java/Rotating A Linked List.java
Labels: hacktoberfest, hacktoberfest-accepted

#23 Create display any message on heart.py
  python/display any message on heart.py
Labels: hacktoberfest, hacktoberfest-accepted

#25 reverse a string
  java/ReverseString.java
Labels: hacktoberfest, hacktoberfest-accepted

#28 added files
  c/givn yr is  leap yr or not.c
  c/integers between n and m.c
  c/large of 2 num.c
  c/largest of 3 nums using && oprt.c
Labels: hacktoberfest, hacktoberfest-accepted

#29 added files
  c/reverse of number.c
  c/roots quadratic eqtn.c
  c/sgpa.c
Labels: hacktoberfest, hacktoberfest-accepted

#30 python
  python/function mul.py
Labels: hacktoberfest, hacktoberfest-accepted

#31 Add files via upload
  python/function sub.py
Labels: hacktoberfest, hacktoberfest-accepted

#36 python
  python/zip.py
Labels: hacktoberfest, hacktoberfest-accepted

#32 Added Prime_Number.cpp
  c++/Prime_Number.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#33 Added 3 JavaScript problems with solution
  javascript/Calculate-BMI.js
  javascript/Even-or-Odd.js
  javascript/MakeUpperCase.js
Labels: hacktoberfest, hacktoberfest-accepted

#34 Added 2 C++ Program
  c++/Sqrt_of_a_number.cpp
  c++/balanced_paranthesis.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#35 added bankprogram.cpp
  c++/bankprogram.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#37 Create harshadNumber.java
  java/harshadNumber.java
Labels: hacktoberfest, hacktoberfest-accepted

#38 convertion of number from decimal number system to binary
  java/binaryToDecimal.java/binaryToDecimal.java
  java/decimalToBinary.java/decimalToBinary.java
Labels: hacktoberfest, hacktoberfest-accepted

#39 Creating a ShellSortingAlgo.py
  python/Creating a ShellSortingAlgo.py
Labels: hacktoberfest, hacktoberfest-accepted

#40 Create Bubble_sort_c++.cpp
  c++/Bubble_sort_c++.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#41 Create Bellman Ford AlgoImplement.java
  Create Bellman Ford AlgoImplement.java
Labels: hacktoberfest, hacktoberfest-accepted

#42 RadixSortingAlgo.java
  java/RadixSortingAlgo.java
Labels: hacktoberfest, hacktoberfest-accepted

#43 SelectionSortAlgo.cpp
  c++/SelectionSortAlgo.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#44 Create BinarySearch.java
  java/BinarySearch.java
Labels: hacktoberfest, hacktoberfest-accepted

#45 Create PalindromeExample.java
  java/PalindromeExample.java
Labels: hacktoberfest, hacktoberfest-accepted

#46 Added Hexadecimal_to_Binary.py
  python/Hexadecimal_to_Binary.py
Labels: hacktoberfest, hacktoberfest-accepted

#47 Clock program in C
  c/Clock.c
Labels: hacktoberfest, hacktoberfest-accepted

#48 Add files via upload
  c/Hand cricket game.c
Labels: hacktoberfest, hacktoberfest-accepted

#49 Added a Butterfly Pattern Program in C++ folder
  .vscode/tasks.json
  c++/butterfly_pattern.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#51 Code for tower of Hanoi problem
  c++/towerOfHanoi.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#50 added password generator
  java/PasswordGenerator.java
Labels: hacktoberfest, hacktoberfest-accepted

#52 Code for printing pascal's triangle
  c++/pascaltriangle.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#59 Rock Paper Scissor
  python/Rock Paper Scissor.py
Labels: hacktoberfest, hacktoberfest-accepted

#53 Fabonacci Series code
  c++/printFabonacciSeries.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#54 Code for spiral traversal of an array
  c++/spiralTraversalofArray.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#55 Create confirm password authentication
  confirm password authentication
Labels: hacktoberfest, hacktoberfest-accepted

#56 Program To Find Largest Number
  javascript/LargestNumber.js
Labels: hacktoberfest, hacktoberfest-accepted

#60 Update README.md
  README.md
Labels: invalid, spam

#62 Create FizzBuzz.py
  python/FizzBuzz.py
Labels: hacktoberfest, hacktoberfest-accepted

#63 Create Password-Generator.py
  python/Password-Generator.py
Labels: hacktoberfest, hacktoberfest-accepted

#61 Paranthesis Checker code.
  c/paranthesisChecker.c
Labels: hacktoberfest, hacktoberfest-accepted

#64 Create Guess The Number.py
  python/Guess The Number.py
Labels: hacktoberfest, hacktoberfest-accepted

#65 Create time complexity of different sorting methods.java
  java/time complexity of different sorting methods.java
Labels: hacktoberfest, hacktoberfest-accepted

#66 BinarySearch.cpp
  c++/BinarySearch.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#68 Create Longest String Chain.cpp
  c++/Longest String Chain.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#69 num-guessing-game added
  c++/num_guessing_game.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#71 InsertionSort.cpp
  c++/InsertionSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#72 Create decoded-string.cpp
  c++/decoded-string.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#73 Second Largest Number file is added
  javascript/second_largest.js
Labels: hacktoberfest, hacktoberfest-accepted

#74 Added a C++ file which has all the fucntions using basic operations
  c++/basicoperationfunction.c++
Labels: hacktoberfest, hacktoberfest-accepted

#75 added evenodd.cpp program
  c++/evenodd.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#76 added dectobin.c program
  c/dectobin.c
Labels: hacktoberfest, hacktoberfest-accepted

#77 Create dectobin.py
  python/dectobin.py
Labels: hacktoberfest, hacktoberfest-accepted

#78 Create LCM.java
  java/LCM.java
Labels: hacktoberfest, hacktoberfest-accepted

#79 Rock,paper ,scissor .C
  c/rps.c
  c/rps.exe
Labels: hacktoberfest, hacktoberfest-accepted

#80 who's your flame
  python/flame.py
Labels: good first issue, hacktoberfest, hacktoberfest-accepted

#86 Added Face Attendace System Project
  python/Face-Attendance-System/AddDataToDatabase.py
  python/Face-Attendance-System/EncodeGenerator.py
  python/Face-Attendance-System/Readme.md
  python/Face-Attendance-System/Resources/Modes/1.png
  python/Face-Attendance-System/Resources/Modes/2.png
  python/Face-Attendance-System/Resources/Modes/3.png
  python/Face-Attendance-System/Resources/Modes/4.png
  python/Face-Attendance-System/Resources/background.png
  python/Face-Attendance-System/dlib package install/dlib-19.22.99-cp310-cp310-win_amd64.whl
  python/Face-Attendance-System/dlib package install/dlib-19.22.99-cp37-cp37m-win_amd64.whl
  python/Face-Attendance-System/dlib package install/dlib-19.22.99-cp38-cp38-win_amd64.whl
  python/Face-Attendance-System/dlib package install/dlib-19.22.99-cp39-cp39-win_amd64.whl
  python/Face-Attendance-System/dlib package install/dlib-19.24.1-cp311-cp311-win_amd64.whl
  python/Face-Attendance-System/main.py
Labels: hacktoberfest, hacktoberfest-accepted

#82 Create mergeSort.cpp
  c++/mergeSort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#83 Priority Queue with comparatores added
  c++/PriorityQueueWithComparatora.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#85 first commit
  java/fibonacci.java
Labels: hacktoberfest, hacktoberfest-accepted

#87 Add an implementation example of radix sort
  java/sort/RadixSorting.java
Labels: hacktoberfest, hacktoberfest-accepted

#89 Add an implementation example of quick sort
  java/sort/QuickSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#90 Add an implementation example of insert sort
  java/sort/InsertSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#91 Sieve Added
  c++/Sieve of Eratosthenes.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#92 Added String_Compression.cpp
  c++/String_Compression.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#93 Sub array sum divisible by K code added
  c++/SubarraysDivisiblebyK.cpp
  c++/SubarraysDivisiblebyK.exe
Labels: hacktoberfest, hacktoberfest-accepted

#94 Rename second_largest.js to Second_largest.js
  javascript/Second_largest.js
Labels: hacktoberfest, hacktoberfest-accepted

#95 Update even or odd.c
  c/even or odd.c
Labels: hacktoberfest, hacktoberfest-accepted

#97 Create Binary.py
  Binary.py
Labels: hacktoberfest, hacktoberfest-accepted

#99 Update sum.java
  java/sum.java
Labels: hacktoberfest, hacktoberfest-accepted

#100 Create ParenthesisChecker.cpp
  c++/ParenthesisChecker.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#101 Insertion sort using Java
  java/InsertionSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#102 Add an Implementation Of MergeSort & Well Explained Using Comments
  java/sort/MergeSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#108 Create ML_program_for_Salary__Estimation__using__K-Nearest__Neighbour
  **Importing Libraries**  !pip install pandas  import pandas as pd #useful for loading the dataset import numpy as np # to perform array  **Choose Dataset from Local Directory**  from google.colab import files uploaded = files.upload()  **Load Dataset**  dataset = pd.read_csv('adult.csv') # load data into a variable dataset  **Summarize Dataset**  print(dataset.shape) #No. of rows and column print(dataset.head(5)) #Top 5 value  **Mapping Salary Data to Binary Value**  income_set = set(dataset['income']) dataset['income'] = dataset['income'].map({'<=50K' : 0, '>50K' :1}).astype(int) print(dataset.head(20))  **Segregate Dataset into X(input/IndependentVariable) and Y(Output/ML_program_for_Salary__Estimation__using__K-Nearest__Neighbour
Labels: hacktoberfest, hacktoberfest-accepted

#114 LCA of BST.java
  LCA of BST.java
Labels: hacktoberfest, hacktoberfest-accepted

#116 Create swap_method.cpp
  c++/swap_method.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#117 Create Python program to search an element in row-wise and column-wis…
  python/Python program to search an element in row-wise and column-wise sorted matrix
Labels: hacktoberfest, hacktoberfest-accepted

#118 CPP program added
  c++/Container with Maximum Water.cpp
  c++/Minimum Sum Subarray Of Given Size.cpp
  c++/PrintKeypad.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#115 stack.java added
  java/Stack.java
Labels: hacktoberfest, hacktoberfest-accepted

#136 Added Machine Learning codes
  Machine Learning/DecisionTree.py
  Machine Learning/FoodTruck.csv
  Machine Learning/KNN.py
  Machine Learning/LogisticRegression.py
  Machine Learning/Mushroom.csv
  Machine Learning/NaiveBayes.py
  Machine Learning/NeuralNetwork.py
  Machine Learning/RandomFprest.py
  Machine Learning/Regression.py
  Machine Learning/SVM.py
Labels: hacktoberfest, hacktoberfest-accepted

#134 Create toDeleteNodeFromLinkedList.cpp
  c++/toDeleteNodeFromLinkedList.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#133 Added Singly Circular Linked List Using C++
  c++/SinglyC.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#132 Added Kadane's algorithm and Jaggered arrays code in C++.
  Jaggered Arrays
  Kadane's Algorithm
Labels: hacktoberfest, hacktoberfest-accepted

#129 Java: Inner class
  java/Outer.java
Labels: hacktoberfest, hacktoberfest-accepted

#127 commit
  java/LinearSearch.java
Labels: hacktoberfest, hacktoberfest-accepted

#126 Create Slicker_Algorithm_Program.cpp
  c++/Slicker_Algorithm.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#125 added notepad using tk (python)
  python/Notepad_using_tk.py
Labels: hacktoberfest, hacktoberfest-accepted

#124 frequency
  java/Freq.java
Labels: hacktoberfest, hacktoberfest-accepted

#123 added bogosort.py file
  bogosort.py
Labels: hacktoberfest, hacktoberfest-accepted

#122 Create GuessTheNumber.java
  java/GuessTheNumber.java
Labels: hacktoberfest, hacktoberfest-accepted

#148 feat: Added snake game in python folder
  python/snake_game.py
Labels: hacktoberfest, hacktoberfest-accepted

#147 CRUD App using Mongo + Spring Boot
  MongoDB/demoapplication/.gitignore
  MongoDB/demoapplication/.mvn/wrapper/maven-wrapper.jar
  MongoDB/demoapplication/.mvn/wrapper/maven-wrapper.properties
  MongoDB/demoapplication/mvnw
  MongoDB/demoapplication/mvnw.cmd
  MongoDB/demoapplication/pom.xml
  MongoDB/demoapplication/src/main/java/com/demoproject/demoapplication/DemoapplicationApplication.java
  MongoDB/demoapplication/src/main/java/com/demoproject/demoapplication/controller/TaskController.java
  MongoDB/demoapplication/src/main/java/com/demoproject/demoapplication/model/Task.java
  MongoDB/demoapplication/src/main/java/com/demoproject/demoapplication/repository/TaskRepository.java
  MongoDB/demoapplication/src/main/java/com/demoproject/demoapplication/service/TaskService.java
  MongoDB/demoapplication/src/main/resources/.env
  MongoDB/demoapplication/src/main/resources/application.properties
  MongoDB/demoapplication/src/test/java/com/demoproject/demoapplication/DemoapplicationApplicationTests.java
Labels: hacktoberfest, hacktoberfest-accepted

#143 Added Linear Regression model in ML folder
  Machine Learning/LinearRegression.py
Labels: hacktoberfest, hacktoberfest-accepted

#144 Binary Search algorithm added in java programs
  java/BinarySearch.java
Labels: hacktoberfest, hacktoberfest-accepted

#142 Added java code for finding Amstrong number
  java/Amstrong.java
Labels: hacktoberfest, hacktoberfest-accepted

#141 Majority Elements
  c++/MajorityElement.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#153 Create Quick Sort Algorithm
  java/Quick Sort Algorithm
Labels: hacktoberfest, hacktoberfest-accepted

#158 added C scripts
  C/Greedy_Knapsack.c
  C/LCS.c
  C/SCS.c
Labels: hacktoberfest, hacktoberfest-accepted

#160 Create Fcfs.cpp
  c++/Fcfs.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#161 Create dictionary in Python
  dictionary in Python
Labels: hacktoberfest, hacktoberfest-accepted

#163 Create Python Program for compound interest
  Python Program for compound interest
Labels: hacktoberfest, hacktoberfest-accepted

#165 Create hangmanGamePython
  python/hangmanGamePython
Labels: hacktoberfest, hacktoberfest-accepted

#166 Create weatherAppPython
  weatherAppPython
Labels: hacktoberfest, hacktoberfest-accepted

#168 Create todoListPython
  todoListPython
Labels: hacktoberfest, hacktoberfest-accepted

#169 Added PalindromeChecker.java
  java/PalindromeChecker.java
Labels: hacktoberfest, hacktoberfest-accepted

#171 Diamond Pattern In CPP
  c++/Dimond_pattern.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#172 Create Insertion.py
  Insertion.py
Labels: hacktoberfest, hacktoberfest-accepted

#173 Create Kruskal.cpp
  c++/Kruskal.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#174 Adding base64 encoder and decoder code cpp
  .DS_Store
  c++/.DS_Store
  c++/Base64_Encoder_Decoder.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#180 added max_value_array
  max_value_arr.py
Labels: hacktoberfest, hacktoberfest-accepted

#178 Create Dijkstra's Algorithm
  c++/DjistraAlgo.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#177 Update: Modified
  C/jump_game.c
  CONTRIBUTING.md
  Code of Conduct.md
  LICENSE
  README.md
  c++/Jaggered Arrays
  c++/Kadane's Algorithm.cpp
  java/Quick Sort Algorithm.java
  python/Insertion.py
  python/Maximum of two numbers in Python.py
  python/Python Program for compound interest.py
  python/Spelling_Correction.py
  python/alarmClockPython.py
  python/bogosort.py
  python/dictionary in Python.py
  python/hangmanGamePython.py
  python/requirement.txt
  python/to make dictionary in python.py
  python/todoListPython.py
  python/weatherAppPython.py
Labels: hacktoberfest, hacktoberfest-accepted

#182 program for problem - Sort an array of 0s, 1s and 2s
  c++/Sort_0_1_2.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#181 Create Insertion Sort Algorithm.c
  C/Insertion Sort Algorithm.c
Labels: hacktoberfest, hacktoberfest-accepted

#184 Create Binarysearch.cpp
  c++/Binarysearch.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#185 Create Quicksort.cpp
  c++/Quicksort.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#188 LeetCode 209 - Minimum Size Subarray Sum
  GO/MinimumSizeSubArraySum/main.go
  README.md
Labels: hacktoberfest, hacktoberfest-accepted

#189 Added Python Program to Scrape data from Website
  python/orielly_website_crawler.py
Labels: hacktoberfest, hacktoberfest-accepted

#191 Create stack.py
  python/stack.py
Labels: hacktoberfest, hacktoberfest-accepted

#192 Added Files for Linked List programs in C++
  c++/CircularLL.cpp
  c++/DoublyLL.cpp
  c++/LoopinLL.cpp
  c++/SearchinLinkedList.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#204 Added JAVA algorithm implementation for insertion sort
  Machine Learning/HumanKeypointsDetection/HumanKeypointDetection.py
  java/InsertSort.java
Labels: hacktoberfest, hacktoberfest-accepted

#201 Create Container With Most Water.cpp
  c++/Container With Most Water.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#200 Create insertion.py
  insertion.py
Labels: hacktoberfest, hacktoberfest-accepted

#198 Create Merge k Sorted lists
  python/Merge k Sorted lists
Labels: hacktoberfest, hacktoberfest-accepted

#195 Treasure island
  python/treasure_island.py
Labels: hacktoberfest, hacktoberfest-accepted

#207 added new solutions for container with most water
  c++/Container With Most Water.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#206 Implementation for Stack Using Java
  Stack java
Labels: hacktoberfest, hacktoberfest-accepted

#205 calculator in C language
  C/calculator.c
Labels: hacktoberfest, hacktoberfest-accepted

#212 Add files via upload
  C/even or odd.c
Labels: hacktoberfest, hacktoberfest-accepted

#211 Created Caesar_Cipher_Encoder_Decoder.cpp
  c++/Caesar_Cipher_Encoder_Decoder.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#210 Create reverse-a-string
  python/reverse-a-string
Labels: hacktoberfest, hacktoberfest-accepted

#209 Add Calculator Program in Python
  python/Calculator.py
Labels: hacktoberfest, hacktoberfest-accepted

#213 Create selectionSort
  Selection sort/selectionSort.py
Labels: hacktoberfest, hacktoberfest-accepted

#232 Pong game in Python
  python/pong game/ball.py
  python/pong game/main.py
  python/pong game/paddle.py
  python/pong game/scoreboard.py
Labels: hacktoberfest, hacktoberfest-accepted

#229 Create binarySearch.py
  binarySearch.py
Labels: hacktoberfest, hacktoberfest-accepted

#226 Create Treasure Island game.py
  Treasure Island game.py
Labels: hacktoberfest, hacktoberfest-accepted

#225 added a bubble sort algorithm in C
  C/added bubble sort algorithm in C
Labels: hacktoberfest, hacktoberfest-accepted

#224 Create LinkedList.java
  java/LinkedList.java
Labels: hacktoberfest, hacktoberfest-accepted

#223 Insertion sort and maxm value in array in cpp
  insertalgo.py
  maxnum.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#222 #0 Create AI_face_landmark Demo
  .DS_Store
  Machine Learning/FaceLandmark/FaceLandmark .ipynb
  Machine Learning/FaceLandmark/README.md
  Machine Learning/FaceLandmark/Test.jpg
  Machine Learning/FaceLandmark/musk.png
  Machine Learning/HumanKeypointsDetection/HumanKeypointDetection.py
Labels: hacktoberfest, hacktoberfest-accepted

#220 Add files via upload
  java/ArrayMinMax.java
  java/FoodOrderApp/FoodOrder.class
  java/FoodOrderApp/FoodOrder.java
  java/HashMapInJava.java
  java/bit_manipn.java
Labels: hacktoberfest, hacktoberfest-accepted

#219 Add Bulk Email Sending Project
  python/Bulk_Email_Sender/hzshashwat.xlsx
  python/Bulk_Email_Sender/script.py
  python/Bulk_Email_Sender/template/index.html
Labels: hacktoberfest, hacktoberfest-accepted

#218 Created CircularQueue in C++
  c++/CircularQueue.cpp
Labels: hacktoberfest, hacktoberfest-accepted

#216 Created a tic tac toe game in c language
  C/tic_tac_toe.c
Labels: hacktoberfest, hacktoberfest-accepted

#214 url_shortener
  python/url_shortener.py
Labels: hacktoberfest, hacktoberfest-accepted

#233 Create caesar_cipher_encoder__decoder.py
  python/caesar_cipher_encoder__decoder.py
Labels: hacktoberfest, hacktoberfest-accepted

#234 Create password_generator.py
  python/password_generator.py
Labels: hacktoberfest, hacktoberfest-accepted

#236 iris data analysis
  Machine Learning/LrisDataset/LrisDataAnalysis.ipynb
  Machine Learning/LrisDataset/LrisDataAnalysis.md
Labels: hacktoberfest, hacktoberfest-accepted
